package view;

public class ConverterGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConverterGUI
     */
    public ConverterGUI() {
        initComponents();
        
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempTxt = new javax.swing.JTextField();
        celsiusLbl = new javax.swing.JLabel();
        resultLbl = new javax.swing.JLabel();
        converterBtn = new javax.swing.JButton();
        temperaturesCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");
        setResizable(false);

        tempTxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tempTxt.setForeground(java.awt.Color.gray);
        tempTxt.setText("Enter a temperature");
        tempTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tempTxt.setPreferredSize(new java.awt.Dimension(111, 28));
        tempTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempTxtFocusLost(evt);
            }
        });
        tempTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTxtActionPerformed(evt);
            }
        });

        celsiusLbl.setText("Celsius to");

        resultLbl.setText("Result ");

        converterBtn.setText("Converter");
        converterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterBtnActionPerformed(evt);
            }
        });

        temperaturesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Farenheit", "Kelvin" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(celsiusLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temperaturesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(converterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celsiusLbl)
                    .addComponent(temperaturesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLbl)
                .addGap(14, 14, 14)
                .addComponent(converterBtn)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTxtActionPerformed
        String temp = controller.ConverterController.converter(tempTxt.getText(), temperaturesCB.getSelectedItem().toString());
        if (temperaturesCB.getSelectedItem().toString().equals("Farenheit"))
            resultLbl.setText("Result " + temp + " °F");
        else if (temperaturesCB.getSelectedItem().toString().equals("Kelvin"))
            resultLbl.setText("Result " + temp + " K");
    }//GEN-LAST:event_tempTxtActionPerformed

    private void tempTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempTxtFocusGained
        if (tempTxt.getText().equals("Enter a temperature")) {
            tempTxt.setText("");
            tempTxt.setFont(new java.awt.Font("Segoe UI", 0, 12));
            tempTxt.setForeground(java.awt.Color.BLACK);
        }
       
    }//GEN-LAST:event_tempTxtFocusGained

    private void tempTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempTxtFocusLost
        if (tempTxt.getText().isEmpty()) {
            tempTxt.setFont(new java.awt.Font("Segoe UI", 2, 12));
            tempTxt.setForeground(java.awt.Color.gray);
            tempTxt.setText("Enter a temperature");
        }
    }//GEN-LAST:event_tempTxtFocusLost

    private void converterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterBtnActionPerformed
        String temp = controller.ConverterController.converter(tempTxt.getText(), temperaturesCB.getSelectedItem().toString());
        if (temperaturesCB.getSelectedItem().toString().equals("Farenheit"))
            resultLbl.setText("Result " + temp + " °F");
        else if (temperaturesCB.getSelectedItem().toString().equals("Kelvin"))
            resultLbl.setText("Result " + temp + " K");
    }//GEN-LAST:event_converterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celsiusLbl;
    private javax.swing.JButton converterBtn;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JTextField tempTxt;
    private javax.swing.JComboBox<String> temperaturesCB;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("\\imgs\\icon_1.png")));
    }
}
